### ISSUE TITLE
Translation files did not appear on first startup

### ISSUE THREAD

**Issue by Lebmay75** [Hxncusik/FastPluginConfigurer#3]
### FastPluginConfigurer version

1.0.9

### Minecraft version

1.16

### What I did

I ran the plugin for the first time and no translation files appeared

### What actually happened

Files with translations did not appear

### What should have happened

The files should have uploaded

### Server logs and FastPluginConfigurer config

[latest.log](https://github.com/user-attachments/files/16081872/latest.log)

**Comment by Hxncusik** [comment]
Fixed in 1.1.0
