### ISSUE TITLE
You can take things out of inventory.

### ISSUE THREAD

**Issue by Lebmay75** [Hxncusik/FastPluginConfigurer#4]
### FastPluginConfigurer version

1.0.9

### Minecraft version

1.16

### What I did

I wrote the command /fpc config PlugManX config.yml and clicked on the item with the shift after which the item appeared in my inventory.

### What actually happened

The item I shift-clicked appeared in my inventory.

### What should have happened

The item I clicked on shouldn't have appeared in my inventory.

**Comment by Hxncusik** [comment]
It is only creative mode feature, in survival mode you can`t place taked items
